// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArh2fcdDAQZbrQVbV9R4C_DGXG4T63yrU',
    appId: '1:152245254989:web:eeb5f24c6aa41f1fa6d504',
    messagingSenderId: '152245254989',
    projectId: 'fluttergram-99d80',
    authDomain: 'fluttergram-99d80.firebaseapp.com',
    storageBucket: 'fluttergram-99d80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBkcIE-ooMg5wozaRHgdUg6yCvi13uMeU',
    appId: '1:152245254989:android:a646822dbed27468a6d504',
    messagingSenderId: '152245254989',
    projectId: 'fluttergram-99d80',
    storageBucket: 'fluttergram-99d80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkGcxikA0y4Daslpwq9d6kETv_3KU85Rw',
    appId: '1:152245254989:ios:3d638a2b8302449ca6d504',
    messagingSenderId: '152245254989',
    projectId: 'fluttergram-99d80',
    storageBucket: 'fluttergram-99d80.appspot.com',
    iosClientId: '152245254989-nebkj4mvmf7dvv5np47nd027ubl7rmit.apps.googleusercontent.com',
    iosBundleId: 'com.woogie.instagram',
  );
}
